server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  servlet:
    context-path: /api
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  application:
    name: xiuyuan-admin
  main:
    allow-bean-definition-overriding: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
    # 字符编码配置已移除，使用默认配置
  data:
    redis:
      host: ${REDIS_HOST:100.69.46.53}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:9}
      password: ${REDIS_PWD:hzcldev888}
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-wait: 30s
          max-idle: 3
          min-idle: 1
    mongodb:
      uri: mongodb://xinbaojian:JD0PjLYMZd1QPrQHyHWF@100.91.153.120:2017/xiuyuan-db?authSource=admin

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token前缀
  token-prefix: Bearer
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: ${TIMEOUT:2592000}
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: ${ACTIVITY_TIMEOUT:2592000}
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: ${IS_CONCURRENT:true}
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: ${IS_SHARE:false}
  # token风格
  token-style: random-64
  # 是否输出操作日志
  is-log: false

logging:
  level:
    xin.xiuyuan.admin: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.data.mongodb.core.convert: debug
    io.lettuce.core.protocol: error
    org.springframework.data.mongodb: debug